apiVersion: v1
kind: ConfigMap
metadata:
  name: github-dependabot-prometheus
data:
  GITHUB_USERNAME: YOUR_GITHUB_USERNAME
  GITHUB_REPONAME: YOUR_GITHUB_REPONAME
  GITHUB_TOKEN: YOUR_GITHUB_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-dependabot-prometheus
  name: github-dependabot-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-dependabot-prometheus
  template:
    metadata:
      annotations:
        ad.datadoghq.com/github-dependabot-prometheus.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/github-dependabot-prometheus.init_configs: |
          [{}]
        ad.datadoghq.com/github-dependabot-prometheus.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8000/metrics",
              "metrics": ["github_dependabot_*"],
              "label_to_hostname": "full_reponame"
            }
          ]
      labels:
        app: github-dependabot-prometheus
    spec:
      containers:
        - name: github-dependabot-prometheus
          image: yuyat/github-dependabot-prometheus
          envFrom:
            - configMapRef:
                name: github-dependabot-prometheus
