name: Test

on: [push]

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - run: go test -race
